### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by NatoBoram** [YTVanced/VancedManager#124]
> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

https://f-droid.org/en/contribute/

**Comment by X1nto** [comment]
Vanced manager installs YouTube Vanced, which itself is a proprietary app, we're not going to make vanced open source because it's not built from source

**Comment by KevinX8** [comment]
This app does not and cannot pass fdroid rules so why are you asking us to submit it there?

**Comment by NatoCMI** [comment]
Ah, I didn't catch this part of the [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/).

> * The software should not download additional executable binary files (e.g. Non-Free addons, auto-updates, etc).

My bad.

While we're waiting for https://github.com/YTVanced/VancedManager/issues/115, is there a way to auto-update the app?

**Comment by KevinX8** [comment]
Yes when you open the app it automatically prompts you to update

**Comment by X1nto** [comment]
You can also manually check for updates from manager settings

**Comment by aha999** [comment]
Wouldn't it be possible if we added a Vanced repository link to fdroid ?

**Comment by KevinX8** [comment]
> Wouldn't it be possible if we added a Vanced repository link to fdroid ?

But manager already updates itself, what is the point

**Comment by NatoBoram** [comment]
A good point would be not having to manage updates manually from the developer's side and not having to update the app manually from the user's side since a package manager is kinda made to deal with this, but now that there's an auto-updater it's not exactly rewarding to add this feature.

A good use case would be to add Vanced, MicroG-Vanced and Vanced Music to a custom F-Droid repo, this way technical users don't have to install the manager… but that's a very limited use case.

**Comment by KevinX8** [comment]
> A good point would be not having to manage updates manually from the developer's side and not having to update the app manually from the user's side since a package manager is kinda made to deal with this, but now that there's an auto-updater it's not exactly rewarding to add this feature.
> 
> A good use case would be to add Vanced, MicroG-Vanced and Vanced Music to a custom F-Droid repo, this way technical users don't have to install the manager… but that's a very limited use case.

Fdroid doesn't support split apks, if it did we wouldn't have needed to make our own package manager, and as you said now it's kinda just pointless anyways

**Comment by ghost** [comment]
> > A good point would be not having to manage updates manually from the developer's side and not having to update the app manually from the user's side since a package manager is kinda made to deal with this, but now that there's an auto-updater it's not exactly rewarding to add this feature.
> > A good use case would be to add Vanced, MicroG-Vanced and Vanced Music to a custom F-Droid repo, this way technical users don't have to install the manager… but that's a very limited use case.
> 
> Fdroid doesn't support split apks, if it did we wouldn't have needed to make our own package manager, and as you said now it's kinda just pointless anyways

The only app you would need to add to F-droid is VancedManager, then everyone who downloads VancedManager from F-droid would use it how they use it now to install everything else. This would make it easier for people to know they're using the real VancedManager and help more people find out about the app.

**Comment by KevinX8** [comment]
> > > A good point would be not having to manage updates manually from the developer's side and not having to update the app manually from the user's side since a package manager is kinda made to deal with this, but now that there's an auto-updater it's not exactly rewarding to add this feature.
> > > A good use case would be to add Vanced, MicroG-Vanced and Vanced Music to a custom F-Droid repo, this way technical users don't have to install the manager… but that's a very limited use case.
> > 
> > Fdroid doesn't support split apks, if it did we wouldn't have needed to make our own package manager, and as you said now it's kinda just pointless anyways
> 
> The only app you would need to add to F-droid is VancedManager, then everyone who downloads VancedManager from F-droid would use it how they use it now to install everything else. This would make it easier for people to know they're using the real VancedManager and help more people find out about the app.

Please scroll up and read the information about the inclusion policy, it can never be on f-droid

**Comment by roke-julian-lockhart** [comment]
“http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003699578” is response “http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003629306”.

You are able to create your own repository. The sole problem is that the operators of the default repository is not desiring addition of proprietary software. Much of my proprietary software is available via F-Droid, because I have added the necessary repositories.

**Comment by KevinX8** [comment]
> You are able to create your own repository. The sole problem is that the operators of the default repository is not desiring addition of proprietary software. Much of my proprietary software is available via F-Droid, because I have added the necessary repositories.

Vanced manager is our own package manager so it doesn't really make sense to put a package manager on a repo for another package manager

**Comment by roke-julian-lockhart** [comment]
“http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003711618” is response to “http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003707750”.

“flatpak” and “snap” are available via “dnf”, “zypper”, and “apt”, all of which are managers of packages that are available for operating-systems that are primarily combinations of GNU Software with Linux. Consequently, causing this to be true for Android, which is merely combination of Bionic – rather than GNU software – and Linux, is not weird.

**Comment by KevinX8** [comment]
> “http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003711618” is response to “http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003707750”.
> 
> “flatpak” and “snap” are available via “dnf”, “zypper”, and “apt”, all of which are managers of packages that are available for operating-systems that are primarily combinations of GNU Software with Linux. Consequently, causing this to be true for Android, which is merely combination of Bionic – rather than GNU software – and Linux, is not weird.

It's another repo to maintain and adds 0 convenience because you have to manually find it and add it, when you could have just installed it in first place. 
For your examples all of those things come with your distro and have those things on their official repos, f droid doesn't come with android and it forbids vanced manager from being on its official repos. I really fail to see any convenience factor from maintaining a custom repo for an app that updates itself

**Comment by roke-julian-lockhart** [comment]
“http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1004256416” is response to “http://github.com/YTVanced/VancedManager/issues/124#issuecomment-1003733840”.

F-Droid is the default manager of packages for some operating-systems. Observation of “http://forum.f-droid.org/t/14185” is able to provide verification.

**Comment by NatoBoram** [comment]
@BEEDELLROKEJULIANLOCKHART, all the points were already made and they refused. Please don't harass them about this issue. Even if it's great and all, they said no, so it's no.

**Comment by X1nto** [comment]
> F-Droid is the default manager of packages for some operating-systems. Observation of “[http://forum.f-droid.org/t/14185”](http://forum.f-droid.org/t/14185%E2%80%9D) is able to provide verification.

Some != all. Even if it is the default marketplace for some "de-googled" ROMs, 95% of the users use ROMs provided by OEMs. Finding Vanced Manager is not hard, the official website is the first thing that comes up when you google "vanced", and the download link for manager is right there. We can't add manager to the official repo because of rules on F-Droid, and making a whole new repo that you have to add manually just for 1 app that installs other apps is really inconvenient.
