### ISSUE TITLE
Please add Shizuku install mode

### ISSUE THREAD

**Issue by griffi-gh** [YTVanced/VancedManager#168]
It works on MIUI without disabling Optimization, but requires adb to activate.

And is there any way to download .apks file to install manually?

**Comment by gurmohanb** [comment]
+1
I have same issue with MIUI. Vanced manager does not work if we do not disable MIUI optimizations and if we do so, all permissions break and apps does not work properly. So after enabling MIUI optimizations, every app that require permission asks us to enable again and its headache to enable permission again specially UPI apps that requires contacts, dialer and message permission.
   So developers, my question is can you add option to install vanced manager through Shizuku because earlier it was easy for us to install .apks files from SAI through Shizuku and Shizuku requires only to enable adb permission from PC and it is not required to disable MIUI optimizations. Thanks.

**Comment by X1nto** [comment]
Won't be added. I myself use MIUI and had no problems with permissions whatsoever. Adding a junk code because of MIUI is not something I will consider doing

**Comment by fcaronte** [comment]
Last MIUI version work bad if you disable MIUI optimization, so shizuku way seem the only "easy" option as now I'm use this way to install vanced YouTube but need to take the splitted apk and use SAI installer because it support shizuku app. @griffi-gh maybe you can use this way too. Manager download the files to "nonroot" folder here
Android/data/com.vanced.manager/files/vanced/
