### ISSUE TITLE
Error Dark/black.apk cannot be read

### ISSUE THREAD

**Issue by skylighdiver** [YTVanced/VancedManager#190]
getting message "Dark/Black.apk Cannot Be Read(Did Storage Get Bla]ocked?) or File Missing"   it gives me a close button when i hit it it just continues showing the install circle until i force close the manager

**Comment by DanteKG** [comment]
I have the same issue. As if black.apk is missing but when i check in "Android/data/com.vanced.manager/files/apks/" black.apk is right there along all the other files.
This happens on root version to be precise and I think it's because of the new root installer introduced in Manager v1.3.0 (Arcturus)
![120846921_343660273631828_3742068975654747317_n](https://user-images.githubusercontent.com/688183/95447185-a9317300-0961-11eb-9515-06abf6f044df.png)

**Comment by X1nto** [comment]
Try updating magisk to see if that solves the issue

**Comment by DanteKG** [comment]
> Try updating magisk to see if that solves the issue

I'm running an older phone with system-mode SuperSU (Android 5.1.1). I tried to downgrade to v1.2.0 Nico to see if it will install on it but it seems lower versions arent allowed to install Vanced

**Comment by X1nto** [comment]
> > Try updating magisk to see if that solves the issue
> 
> I'm running an older phone with system-mode SuperSU (Android 5.1.1). I tried to downgrade to v1.2.0 Nico to see if it will install on it but it seems lower versions arent allowed to install Vanced

SuperSU is not supported by us, however magisk is fully supported, so I would recommend using magisk instead of SuperSU

**Comment by 007Nafiz** [comment]
> > > Try updating magisk to see if that solves the issue
> > 
> > 
> > I'm running an older phone with system-mode SuperSU (Android 5.1.1). I tried to downgrade to v1.2.0 Nico to see if it will install on it but it seems lower versions arent allowed to install Vanced
> 
> SuperSU is not supported by us, however magisk is fully supported, so I would recommend using magisk instead of SuperSU

I have been using the latest version of magisk in  (Android 5.1.1). The latest vanced manager used to have this problem. but after some time it stopped. but now when I try to install sometimes it doesn't, after downloading it stops or an unlimited loop continues. but it gets installed in the background but the loop doesn.t stop. then if I stop manager and runs youtube, it runs quite flawlessly. But the real problem is if by any chance I restart my device, youtube reverts back to its stock version

**Comment by DanteKG** [comment]
I like how the conclusion to this issue is "oh yeah it's totally normal that you can't install root vanced" 
*issue closed*

**Comment by X1nto** [comment]
> I like how the conclusion to this issue is "oh yeah it's totally normal that you can't install root vanced" 
> *issue closed*

The conclusion is you should use magisk instead of any other su binary

**Comment by DanteKG** [comment]
@X1nto i know Magisk is the de facto standard root but the thing is that some Samsung phones will read the modified boot image and prevent the phone from booting ("Custom binary blocked by FRP lock") if you have a Google account signed in (which activates the FRP lock).

Doesn't matter too much anyway. If magisk is needed only for installation of vanced and not for it's running then when a new version comes out we can sign out of google, switch to magisk, install vanced, switch back to supersu and sign into google again

**Comment by X1nto** [comment]
> @X1nto i know Magisk is the de facto standard root but the thing is that some Samsung phones will read the modified boot image and prevent the phone from booting ("Custom binary blocked by FRP lock") if you have a Google account signed in (which activates the FRP lock).
> 
> Doesn't matter too much anyway. If magisk is needed only for installation of vanced and not for it's running then when a new version comes out we can sign out of google, switch to magisk, install vanced, switch back to supersu and sign into google again

We would definitely fix this issue if this depended on manager itself but since it fully depends on SuperSU, I doubt there's nothing we can do
