### ISSUE TITLE
Official youtube installed when try to install youtube vanced

### ISSUE THREAD

**Issue by sachindanav** [YTVanced/VancedManager#197]
- I installed the App from [vanced.app](https://vanced.app), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisation
- For root users: I disabled apk Signature Verification

**Phone Specifications:**
- Brand:oppo
- Operating System:android
- Android Version:6.1
- Vanced Manager Version:1.3.1

**I tried to update vanced from vanced manager but it install official youtube app instead of youtube vanced i try to uninstall youtube with titanium backup and install but still its installing official app please fix it**

**Comment by Puatikskao** [comment]
Same issue with me.

I've been happily using rooted vanced for years, version 13.xxx (don't remember exact number) and it was just fine until a non dismissable update screen blocked my usage. So I tried updating vanced using the manager but it installed the stock version instead.

I'm not sure if it makes a difference but I somehow rigged my phone to think that my last vanced version is the factory version, so if I say "uninstall all YouTube updates and return to factory version" it will go back to vanced 13.xxx. Maybe this is why the manager installed the stock version instead? Somehow that setup confused it? Anyway I can't use YouTube ad-free now because I can't bypass the nag on the old version and the new version is stock.

Anyone know how I can convince the manager to install actual vanced and not the stock version? Or will I have to go into system/app and do it all manually instead? (always tons of potential for crashes and errors doing that so I'd rather avoid it) 

Thanks!

PS: I tried just using non root instead but it says my Google account already exists on the phone so I can't sign into micro unless I delete my Google account from the phone then re-add it? I think this would probably complicate more than fix things so I'd rather just get the root version installed properly.

**Comment by XspeedPL** [comment]
I have the same issue, the root installation method seems broken, since the app hangs during the operation. Then if I forcefully stop it, I'm left with regular YouTube.

**Comment by technic-Angel6644** [comment]
It would be helpful if all of you would provide more Information on android version, rom and phone brand.

**Comment by XspeedPL** [comment]
My device is Sony Xperia XZ Premium, latest stock Android Pie.
Tested with Magisk 21.0, Magisk Manager 8.0.2, EdXposed 4.5.7, signature verification disabled by LP 8.9.3, SELinux in enforcing mode.

**Comment by XspeedPL** [comment]
I just noticed something weird though, Vanced Manager seems to generate two directories for YouTube in `/data/app/`. Both have `com.google.android.youtube` as prefix package name.
In one there is just base.apk file, while in the other there are is the same base.apk, but also splik_config apk files.
This sounds like the root of the problem.

**Comment by X1nto** [comment]
Try updating your magisk, it solved the problem for some users

**Comment by XspeedPL** [comment]
I use the latest canary (311) of Magisk Manager. As far as I know, there are no problems accessing root.
Also, I've tried building the app using latest sources on dev branch, but it still fails the same way.

**Comment by xydche** [comment]
I have the same issue too. 
vanced: root version with black theme
CorePatcher 2.2 ,"APK signature verification" disabled
Vanced Manager 1.3.1
Oneplus 7T OOS 10.3.6
Magisk 20.4
I can only install the YTB vanced 15.40.37 using SAI.

**Comment by 777shibby** [comment]
Same issue.
Standard YT app installed instead of vanced
Vanced settings present but it sends me back to YT start screen.


OnePlus 2 A2003
Android 6.1
OxygenOS 3.6.1
root
Magisk: 20.4
"APK signature verification" disabled
Vanced manager: 2.0.1
Vanced: latest - dark theme

**Comment by X1nto** [comment]
Try with new manager and make sure you don't exit app when it's installing

**Comment by xydche** [comment]
> I have the same issue too.
> vanced: root version with black theme
> CorePatcher 2.2 ,"APK signature verification" disabled
> Vanced Manager 1.3.1
> Oneplus 7T OOS 10.3.6
> Magisk 20.4
> I can only install the YTB vanced 15.40.37 using SAI.

manager2.1.0, the same issue.

**Comment by varuzam** [comment]
The version 1.3.1 works for me. 2.0 2.1 dont

**Comment by l4jos** [comment]
I'm having the same issue on CrDroid, and today again on a fresh LineageOS install as well.

My first idea that I was thinking about when I noticed the white-red icon instead of the darker one from vanced was 
like Play Store is replacing the one from vanced.app with the official Youtube app. Just, Google's default offensive behaviour.
And it does not matter if the ROM is flashed along with with GAPPS (or BiTGApps).

Something triggers an update at the Play Store.

**Comment by l4jos** [comment]
I'm having the same issue on CrDroid, and today again on a fresh LineageOS install as well.

My first idea that I was thinking about when I noticed the white-red icon instead of the darker one from vanced was
like Play Store is replacing the one from vanced.app with the official Youtube app. Just, Google's default offensive behaviour.
And it does not matter if the ROM is flashed along with with GAPPS (or BiTGApps).

Something triggers an update at the Play Store.

**Comment by X1nto** [comment]
See if it's resolved in 2.2

**Comment by X1nto** [comment]
I'm gonna consider this fixed. If anyone still has the issue, feel free to comment and I'll reopen
