### ISSUE TITLE
[Question] Download path 

### ISSUE THREAD

**Issue by Pawloland** [YTVanced/VancedManager#27]
App is downloading some files, which are necessary to install yt vanced. Where are they stored? I searched in download folder of internal storage and app's folders inside android/data, android/media and android/obb but couldn't find any of the previously downloaded files. 

So the question is: what is the download path?

**Comment by X1nto** [comment]
Hi, as you can see app doesn't require permissions for external storage access, we could just download into /Download folder in your sdcard directory but since Android R will be forcing scoped storage, we thought that it would be easier to save downloads to in-app storage. Vanced split apk files are stored in `/data/data/com.vanced.manager/cache`, microg and manager are downloaded in `/data/data/com.vanced.manager/files`
