### ISSUE TITLE
[Feature Request] "Open File Location" for APK folder

### ISSUE THREAD

**Issue by SquadCraftFTW** [YTVanced/VancedManager#364]
My suggestion is to add an android equivalent of windows' "open file location" if an update or installation fails.

Just for context, I am running a MIUI phone, but disabling MIUI optimisation, the suggested solution by Vanced, causes me serious issues with battery and stability.

Manually navigating with a file explorer to the Vanced manager directory circumvents this issue for me, however it takes a long time to do so and I also forget the location of the directory. I feel this could be a suitable compromise for MIUI phones, especially for the slightly less tech savvy.

**Comment by X1nto** [comment]
We might just add an option to change download location as well

**Comment by szaboariel** [comment]
I'm useing Huawei P30 Lite and the Venced Manger chras for me too.

**Comment by alperovitz** [comment]
> We might just add an option to change download location as well

That's ok but my app is missing the icon

**Comment by alperovitz** [comment]
I think I have it so everyone can get my copy from Google drive

**Comment by alperovitz** [comment]
P.s don't download load 15.4 than try to install just get the micro g app part of the manger

**Comment by alperovitz** [comment]
Than login the microG than in install my google drive copy you will see it is youtube 16.04.34

**Comment by X1nto** [comment]
A quick update: Due to scoped storage, we won't be able to let you choose a directory where downloaded files are saved. However, I'm planning on moving downloads under `/Downloads/Vanced Manager` and logs under `/Documents/Vanced Manager` as they're more intuitive than /Android/data/com.vanced.manager/files

**Comment by mario0318** [comment]
> A quick update: Due to scoped storage, we won't be able to let you choose a directory where downloaded files are saved. However, I'm planning on moving downloads under `/Downloads/Vanced Manager` and logs under `/Documents/Vanced Manager` as they're more intuitive than /Android/data/com.vanced.manager/files

Would this option allow for or at least implement a method for the manager to detect if the corresponding app files already exist so that it doesn't need to download them all over each time?

For example, I've got shoddy signal and no wifi where I live. The issue with Vanced apps crashing after several days is very much present and the often immediate fix is to reinstall through the Vanced manager. However, it makes little sense that if I had just downloaded let's say black+15.4x+stock+dpi and the install failed, or the app was closed by mistake, that it would have to redownload those very same files for the same version of the app. It goes for YouTube Music as well. What's the point of having a "clear downloaded files" option in settings if not clearing it has no benefit other than space reduction?

**Comment by X1nto** [comment]
> > A quick update: Due to scoped storage, we won't be able to let you choose a directory where downloaded files are saved. However, I'm planning on moving downloads under `/Downloads/Vanced Manager` and logs under `/Documents/Vanced Manager` as they're more intuitive than /Android/data/com.vanced.manager/files
> 
> Would this option allow for or at least implement a method for the manager to detect if the corresponding app files already exist so that it doesn't need to download them all over each time?
> 
> For example, I've got shoddy signal and no wifi where I live. The issue with Vanced apps crashing after several days is very much present and the often immediate fix is to reinstall through the Vanced manager. However, it makes little sense that if I had just downloaded let's say black+15.4x+stock+dpi and the install failed, or the app was closed by mistake, that it would have to redownload those very same files for the same version of the app. It goes for YouTube Music as well. What's the point of having a "clear downloaded files" option in settings if not clearing it has no benefit other than space reduction?
> 
> Wouldn't implementing such a check for existing files in cache save HUGE amounts of traffic by  eliminating this redundancy on the servers they are hosted on? 

That already exists for nonroot. Currently it's not possible to implement it for root

**Comment by X1nto** [comment]
Unfortunately due to the fact that some popular file explorers don't support folder using an intent, I was unable to add the feature
