### ISSUE TITLE
Save to playlist not organized

### ISSUE THREAD

**Issue by neverstop123** [YTVanced/VancedManager#381]
When viewing any video and you press save, the playlist is shown in recently added format. There's no way to change this to A-Z format, I have A-Z format selected in library>playlist and the playlist shows fine there.

**Comment by szaboariel** [comment]
How can i upload videos in YouTube Vanced without opening the browser and search YouTube.com ant then go to the profiles and click the upload button?because if u tried to upload in the original YouTube, it won't let me, it seys (non app can do this) like I can't open the uploading window eader in YouTube Vanced. Pls some one can halp me?

**Comment by X1nto** [comment]
These issues are not related to manager
