### ISSUE TITLE
API error, stopping all downloads.

### ISSUE THREAD

**Issue by MrInterBugs** [YTVanced/VancedManager#450]
**Phone Specifications:**
- Brand: Sony Xperia 1 II + Nintendo Switch
- Operating System: Sony Stock + Lineage OS
- Android Version: 11
- Vanced Manager Version: 2.5.1

**Please describe the problem you are having in as much detail as possible:**
API seems to be returning with an error, may be server sided?

**Steps to reproduce:**
Install vanced manager and try and download any of the appilcations.

**Further details:**
N/A

**Comment by X1nto** [comment]
BEFORE ANYONE COMMENTS ANYTHING I NEED Y'ALL TO CALM DOWN

As always servers are down, might need some time to recover since OVH servers got recently burned and we only have 1 active server now instead of 3. Because of that, only 1 server gets all the traffic and, well, it just shuts down. The only thing I want to ask you is to not comment with "I have the same issue"

**Comment by MrInterBugs** [comment]
I won't close this myself, however it seems that the server in use has stabilized a bit now and is usable. Managed to update with no issues.

**Comment by X1nto** [comment]
Closing the issue
