### ISSUE TITLE
Why NOT another Magisk Module?

### ISSUE THREAD

**Issue by SubZero5** [YTVanced/VancedManager#50]
Vanced, in the old times, used to work great as a Magisk Module.
So why isn't there any new Module for Magisk?
Is it that hard?

**Comment by X1nto** [comment]
It's not hard, it's literally impossible because vanced requires you to disable signature verification, which can't be done using a magisk module

**Comment by SubZero5** [comment]
Can it be renamed to another app so that it does not replace the original app?

**Comment by X1nto** [comment]
You'll need microg, that'll eliminate whole purpose of root version

**Comment by KevinX8** [comment]
Bruh are you for real, the issue is to use Google play services the app must have the original YouTube signature, regardless of package name. If you change package name then it also probably wouldn't work anyways as play services will not give it the correct data. The whole point of root version is to avoid microg so yeah play services working is a must.
