### ISSUE TITLE
[Bug]: Vanced Manager gives "unable to open file: /data/local/tmp/split_config.arm64_v8a.apk" error when attempting to install

### ISSUE THREAD

**Issue by KirbyFan102** [YTVanced/VancedManager#697]
### Device

Device: Samsung Galaxy M31
Operating System: Android
Android Version: 10

### Version

2.6.1

### Bug Description

This occurs when trying to install the app. I already uninstalled all the youtube updates, so it should work, right?
I'm not sure if the update to the manager might be causing it, or what.

### Additional checks

- [X] This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.

**Comment by Ante0** [comment]
Same problem here. I previously had YouTube vanced installed but it seems to have installed regular updates over night, and now I can't reinstall.

Edit: ok so it has nothing to do with play store updating YouTube, that was on me as I previously wiped play stores data so auto update re-enabled.
However, the bug is in 2.6.1 manager. 2.6.0 installs both YT and Music fine, you just need to stop the manager update after you have installed 2.6.0 so it doesn't update.

**Comment by magictomagic** [comment]
Same to me in redmik30 pro with unable to open file: /data/local/tmp/split_config.arm64_v8a.apk

**Comment by KirbyFan102** [comment]
> 
> 
> Same problem here. I previously had YouTube vanced installed but it seems to have installed regular updates over night, and now I can't reinstall.
> 
> Edit: ok so it has nothing to do with play store updating YouTube, that was on me as I previously wiped play stores data so auto update re-enabled. However, the bug is in 2.6.1 manager. 2.6.0 installs both YT and Music fine, you just need to stop the manager update after you have installed 2.6.0 so it doesn't update.

Thank you, installing the previous version of Vanced Manager worked! Hope the vanced team manages to fix whatever bug is present in version 2.6.1.

**Comment by X1nto** [comment]
I'm investigating the issue, seems to be related to the recent commit 6ed72d3b65b497d89edc02849090473d07404cce, I'll either try to fix it or revert the commit.

**Comment by X1nto** [comment]
should be fixed with 2.6.2
