### ISSUE TITLE
Can you add YT Music to the mix

### ISSUE THREAD

**Issue by rypz79** [YTVanced/VancedManager#93]
It uses MicroG as YTVA 
IDK if it's the same team that's moding these apps but it will be nice to updates for both in the same app.

GJ guys
TIA![Screenshot_20200726-145033_Vanced microG.jpg](https://user-images.githubusercontent.com/28814757/88478317-141d0180-cf50-11ea-9e4f-0bba04eacdca.jpg)

**Comment by X1nto** [comment]
We're adding apps from Vanced, not from other teams

**Comment by DraconicNEO** [comment]
There actually is a YTVanced Music version from the Vanced team

**Comment by X1nto** [comment]
We're not adding YT Kids Vanced either

**Comment by Mattis6666** [comment]
the YTVanced music you are talking about is an app the developer of vanced made for himself, not stable at all and not supported or updated. Due to popular request, there's been an April fools release of it branded as YouTube Kids but this is not an official release, just a joke.

There are no plans to support or develop it further or make an official release
